apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployments.yaml
  - ingress.yaml
  - model-loader-job.yaml

images:
  - name: personal-goi-api
    newName: ghcr.io/your-org/personal-goi-api
    newTag: latest
  - name: personal-goi-ui
    newName: ghcr.io/your-org/personal-goi-ui
    newTag: latest