apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: personal-goi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-data
  namespace: personal-goi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi